invoice-de/src/main/java/com/camunda/fox/showcase/invoice/de/ApproveInvoiceController.java
package com.camunda.fox.showcase.invoice.de;

import javax.enterprise.inject.Model;
import javax.inject.Inject;

import org.activiti.cdi.BusinessProcess;

@Model
public class ApproveInvoiceController {

  private boolean approved;

  @Inject
  private BusinessProcess businessProcess;

  public boolean isApproved() {
    return approved;
  }

  public void setApproved(boolean approved) {
    this.approved = approved;
    businessProcess.setVariable("approved", approved);
  }
}

invoice-de/src/main/java/com/camunda/fox/showcase/invoice/de/PutCommentController.java
package com.camunda.fox.showcase.invoice.de;

import java.io.IOException;

import javax.enterprise.context.Conversation;
import javax.enterprise.inject.Instance;
import javax.enterprise.inject.Model;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.mail.MessagingException;

import org.activiti.engine.TaskService;
import org.activiti.engine.task.Task;

import com.camunda.fox.client.impl.web.TaskForm;

@Model
public class PutCommentController {

	private String comment = null;
	private String newAssignee;
	private boolean email = false;
	private String activityID;

	@Inject
	private Instance<Conversation> conversationInstance;

	@Inject
	private TaskForm taskForm;

	@Inject
	private Task task;

	@Inject
	private TaskService taskService;

	public String getNewAssignee() {
		return newAssignee;
	}

	public void setNewAssignee(String newAssignee) {
		this.newAssignee = newAssignee;
	}

	public boolean isEmail() {
		return email;
	}

	public void setEmail(boolean email) {
		this.email = email;
	}

	public String getActivityID() {
		return activityID;
	}

	public void setActivityID(String activityID) {
		this.activityID = activityID;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public void submit() throws IOException {
		if (!comment.isEmpty()) addComment();
		taskForm.completeTask();
	}

	public void addComment() {

		taskService.addComment(task.getId(), task.getProcessInstanceId(),
				comment);
		this.comment = null;
	}

	public void delegate(String callbackUrl) throws IOException,
			MessagingException {

		addComment();
		taskService.setAssignee(task.getId(), this.newAssignee);

		// conversation is ended (otherwise the
		// redirect will end up in an exception)
		conversationInstance.get().end();
		FacesContext.getCurrentInstance().getExternalContext()
				.redirect(callbackUrl);

	}

}

invoice-de/src/main/java/com/camunda/fox/showcase/invoice/de/servlet/ProcessDiagramServlet.java
package com.camunda.fox.showcase.invoice.de.servlet;

import java.io.IOException;
import java.io.InputStream;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.activiti.engine.RepositoryService;
import org.activiti.engine.repository.ProcessDefinition;
import org.apache.commons.io.IOUtils;


@WebServlet(value = "/processDiagram", loadOnStartup = 1)
public class ProcessDiagramServlet extends HttpServlet {

  private static final long serialVersionUID = 1L;

  @Inject
  private RepositoryService repositoryService;

  @Override
  protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {    
    String processDefinitionId = request.getParameter("processDefinitionId");    
    if (processDefinitionId==null) {
    	String processDefinitionKey = request.getParameter("processDefinitionKey");
    	
    	ProcessDefinition pdef = repositoryService.createProcessDefinitionQuery().processDefinitionKey(processDefinitionKey).latestVersion().singleResult();
    	
    	processDefinitionId = pdef.getId();
    }
    
    InputStream processDiagram = repositoryService.getProcessDiagram(processDefinitionId);

    response.setContentType("image/png");
    response.getOutputStream().write(IOUtils.toByteArray(processDiagram));
  }
}

invoice-de/src/main/java/com/camunda/fox/showcase/invoice/de/tasklist/ProcessDiagramController.java
package com.camunda.fox.showcase.invoice.de.tasklist;

import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;
import javax.inject.Named;

import org.activiti.cdi.BusinessProcess;
import org.activiti.engine.HistoryService;
import org.activiti.engine.RepositoryService;
import org.activiti.engine.RuntimeService;
import org.activiti.engine.TaskService;
import org.activiti.engine.history.HistoricActivityInstance;
import org.activiti.engine.history.HistoricTaskInstance;
import org.activiti.engine.repository.DiagramLayout;
import org.activiti.engine.repository.DiagramNode;
import org.activiti.engine.runtime.ProcessInstance;
import org.activiti.engine.task.Comment;


@Named
public class ProcessDiagramController {

  @Inject
  private RuntimeService runtimeService;

  @Inject
  private RepositoryService repositoryService;

  @Inject
  private HistoryService historyService;

  @Inject
  private BusinessProcess businessProcess;

  @Inject
  private TaskService taskService;
  
 
  private ProcessInstance getCurrentProcessInstance() {
    return businessProcess.getProcessInstance();
  }

  public List<PositionedHistoricActivityInstance> getTraversedFlowNodes() {
    ArrayList<PositionedHistoricActivityInstance> alist = new ArrayList<PositionedHistoricActivityInstance>();

    ProcessInstance processInstance = getCurrentProcessInstance();

    if (processInstance != null) {
      DiagramLayout processDiagramLayout = repositoryService.getProcessDiagramLayout(processInstance.getProcessDefinitionId());
      
      List<HistoricActivityInstance> hlist = historyService.createHistoricActivityInstanceQuery().processInstanceId(processInstance.getId()).list();

      for (HistoricActivityInstance hact : hlist) {
        if (hact.getEndTime() != null) {
           PositionedHistoricActivityInstance pact = new PositionedHistoricActivityInstance(hact, processDiagramLayout.getNode(hact.getActivityId()));
          alist.add(pact);
          
        }
      }
    }

    return alist;
  }

  public List<PositionedHistoricTaskInstance> getTraversedTasks() {
	  	ArrayList<PositionedHistoricTaskInstance> alist = new ArrayList<PositionedHistoricTaskInstance>();
	    ProcessInstance processInstance = getCurrentProcessInstance();

	    if (processInstance != null) {
	      DiagramLayout processDiagramLayout = repositoryService.getProcessDiagramLayout(processInstance.getProcessDefinitionId());
	      List<HistoricTaskInstance> hlist = historyService.createHistoricTaskInstanceQuery().processInstanceId(processInstance.getId()).orderByHistoricActivityInstanceStartTime().asc().list();
	      for (HistoricTaskInstance htask : hlist) {
	    	  if (htask.getEndTime() != null) {
	        	PositionedHistoricTaskInstance ptask = new PositionedHistoricTaskInstance(htask, processDiagramLayout.getNode(htask.getTaskDefinitionKey()));
	        	alist.add(ptask);
	        }
	      }
	    }
	    return alist;
	  }

  public List<PositionedHistoricTaskDefinition> getTraversedTaskDefinitions() {
	  	ArrayList<PositionedHistoricTaskDefinition> alist = new ArrayList<PositionedHistoricTaskDefinition>();

	    ProcessInstance processInstance = getCurrentProcessInstance();

	    if (processInstance != null) {
	      DiagramLayout processDiagramLayout = repositoryService.getProcessDiagramLayout(processInstance.getProcessDefinitionId());
	      
	      //order by taskName as workaround because orderByTaskDefinitionKey is not working. This is not really safe!
	      List<HistoricTaskInstance> hlist = historyService.createHistoricTaskInstanceQuery().processInstanceId(processInstance.getId()).orderByTaskName().asc().list();

	      int i=0;
	      for (HistoricTaskInstance htask : hlist) {
	    	  if (htask.getEndTime() != null) {
	    		  if (i>0) {
		    		  if (alist.get(i-1).getTaskDefinitionKey().equals(htask.getTaskDefinitionKey())) {
		        		alist.get(i-1).taskInstances.add(htask);
		        	} else {
		        		PositionedHistoricTaskDefinition ptask = new PositionedHistoricTaskDefinition(htask, processDiagramLayout.getNode(htask.getTaskDefinitionKey()));
		  	          	alist.add(ptask);
		  	          	i++;
		        	}
	    		  } else {
		        		PositionedHistoricTaskDefinition ptask = new PositionedHistoricTaskDefinition(htask, processDiagramLayout.getNode(htask.getTaskDefinitionKey()));
		  	          	alist.add(ptask);
		  	          	i++;
	    		  }
	        }
	      }
	    }
	    return alist;
	  }


  
  
  public List<DiagramNode> getActiveActivityBoundsOfLatestProcessInstance() {
    ArrayList<DiagramNode> list = new ArrayList<DiagramNode>();
    ProcessInstance processInstance = getCurrentProcessInstance();
    if (processInstance != null) {
      DiagramLayout processDiagramLayout = repositoryService.getProcessDiagramLayout(processInstance.getProcessDefinitionId());
      List<String> activeActivityIds = runtimeService.getActiveActivityIds(processInstance.getId());
      for (String activeActivityId : activeActivityIds) {
        list.add(processDiagramLayout.getNode(activeActivityId));
      }
    }
    return list;
  }
  
  public List<Comment> getCommentsOfLastHistoricTask() {
    ProcessInstance processInstance = getCurrentProcessInstance();
    List<HistoricTaskInstance> hlist = historyService.createHistoricTaskInstanceQuery().processInstanceId(processInstance.getId()).orderByHistoricTaskInstanceEndTime().desc().list();
	if (hlist.get(0).getEndTime() != null) {
	    return getTaskComments(hlist.get(0).getId());		
	} else {
		return null;
	}
  }
  
  public String getTaskComment (String taskId) {
	  String comment = "";
	  if (!taskService.getTaskComments(taskId).isEmpty()) comment = taskService.getTaskComments(taskId).get(0).getFullMessage();
      return comment;
  }
  
  public List<Comment> getTaskComments (String taskId) {
	  return taskService.getTaskComments(taskId);
  }

}

invoice-de/src/main/java/com/camunda/fox/showcase/invoice/de/tasklist/TaskListController.java
package com.camunda.fox.showcase.invoice.de.tasklist;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.activiti.engine.IdentityService;
import org.activiti.engine.identity.User;

@Named
@SessionScoped
public class TaskListController implements Serializable {

  private static final long serialVersionUID = 1L;

  @Inject
  private IdentityService identityService;

  public List<User> getUsersList() {
    return identityService.createUserQuery().list();
  }
 
}

invoice-de/src/main/webapp/approveInvoice.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="WEB-INF/templates/template.xhtml">
	
<ui:define name="metadata">
    <f:metadata>
      <f:viewParam id="taskId" name="taskId" />
      <f:viewParam id="callbackUrl" name="callbackUrl" />
      <f:event type="preRenderView" listener="#{fox.taskForm.startTask(taskId, callbackUrl)}" />
    </f:metadata>
</ui:define>
	
<ui:define name="form">
		<div class="control-group">
			<label class="control-label" for="approval">Freigeben</label>
		    <div class="controls">
			    <h:selectOneMenu id="approval" value="#{approveInvoiceController.approved}">
					<f:selectItem itemValue="true" itemLabel="Ja" />
					<f:selectItem itemValue="false" itemLabel="Nein" />					
				</h:selectOneMenu>				
			</div>
		</div>
</ui:define>

</ui:composition>

invoice-de/src/main/webapp/assignApprover.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="WEB-INF/templates/template.xhtml">

	<ui:define name="metadata">

		<f:metadata>
			<f:viewParam id="taskId" name="taskId" />
			<f:viewParam id="callbackUrl" name="callbackUrl" />
			<f:event type="preRenderView"
				listener="#{fox.taskForm.startTask(taskId, callbackUrl)}" />
		</f:metadata>
	</ui:define>

	<ui:define name="form">
		<div class="control-group">
			<label class="control-label" for="creditor">Kreditor</label>
			<div class="controls">
				<h:inputText id="creditor" value="#{processVariables['creditor']}"
					size="40" maxlength="100" required="true"
					requiredMessage=" Pflichtfeld!" />
				<h:message for="creditor" />
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="date">Rechnungsdatum</label>
			<div class="controls">
				<div class="input-append date" id="dp3" data-date="28.04.1979"
					data-date-format="dd.mm.yyyy">
					<h:inputText class="date-picker" id="date"
						value="#{processVariables['invoice_date']}" required="true"
						requiredMessage=" Pflichtfeld!">
						<f:convertDateTime pattern="dd.MM.yyyy" />
					</h:inputText>
				</div>
				<h:message for="date" />
				<script type="text/javascript">
					//Dates panel
					$('.date-picker').datepicker({
						'format' : 'dd.mm.yyyy',
						'language' : 'de',
						'weekStart' : 1,
						'autoclose' : true
					});
				</script>

			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="approver">Freigebender</label>
			<div class="controls">
				<h:selectOneMenu id="approver"
					value="#{processVariables['approver']}">
					<f:selectItems value="#{taskListController.usersList}"
						var="v_user" itemLabel="#{v_user.id}" itemValue="#{v_user.id}"></f:selectItems>
				</h:selectOneMenu>
				<br />
			</div>
		</div>
	</ui:define>

</ui:composition>

invoice-de/src/main/webapp/clarifyInvoice.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="WEB-INF/templates/template.xhtml">
	
<ui:define name="metadata">
    <f:metadata>
      <f:viewParam id="taskId" name="taskId" />
      <f:viewParam id="callbackUrl" name="callbackUrl" />
      <f:event type="preRenderView" listener="#{fox.taskForm.startTask(taskId, callbackUrl)}" />
    </f:metadata>
</ui:define>

	
	<ui:define name="form">
		<div class="control-group">
			<label class="control-label" for="result">Ergebnis der Kl&#228;rung</label>
		    <div class="controls">
				<h:selectOneMenu id="result" value="#{processVariables['clarified']}">
					<f:selectItem itemValue="yes" itemLabel="Erneut freizugeben"/>
					<f:selectItem itemValue="no" itemLabel="Rechnung verwerfen"/>
				</h:selectOneMenu>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="approver">Neuer Freigebender</label>
		    <div class="controls">
				<h:selectOneMenu id="approver" value="#{processVariables['approver']}">
					<f:selectItems value="#{taskListController.usersList}" var="v_user" 
					itemLabel="#{v_user.id}" itemValue="#{v_user.id}"></f:selectItems>
				</h:selectOneMenu><br/>
			</div>
		</div>
	</ui:define>

</ui:composition>

invoice-de/src/main/webapp/preparePayment.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="WEB-INF/templates/template.xhtml">
	
    
<ui:define name="metadata">
    <f:metadata>
      <f:viewParam id="taskId" name="taskId" />
      <f:viewParam id="callbackUrl" name="callbackUrl" />
      <f:event type="preRenderView" listener="#{fox.taskForm.startTask(taskId, callbackUrl)}" />
    </f:metadata>
</ui:define>

	
	<ui:define name="form">
		<div class="control-group">
			<label class="control-label" for="approver">PDF Archiv</label>
			<div class="controls">
				<h:selectOneMenu id="repo"
					value="#{processVariables['repo']}" >
					<f:selectItem  itemValue="local" itemLabel="Lokal" />
					<f:selectItem  itemValue="alfresco" itemLabel="Alfresco ECM 4"/>
					<f:selectItem  itemValue="svn" itemLabel="Subversion"/>
				</h:selectOneMenu>
				<br />
			</div>
		</div>	
	</ui:define>

</ui:composition>

invoice-de/src/main/webapp/startwas.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

	<h:head>
		<f:metadata>
		    <f:viewParam id="processDefinitionKey" name="processDefinitionKey" />
			<f:viewParam id="callbackUrl" name="callbackUrl" />
		</f:metadata>
		<title>Neue Rechnung</title>
		<h:outputStylesheet name="css/bootstrap.css" />
	</h:head>
	<h:body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container-fluid" style="padding: 0;">
					<a class="brand" href="#{callbackUrl}"
						style="margin: 0 0 0 17px; padding: 0;"><img
						src="../../tasklist/resources/img/FoxTasklist_white.png"
						alt="camunda fox - task list" /></a>
				</div>
			</div>
		</div>
		<div class="container" style="padding-top: 80px;">
			<h1>Rechnung hochladen</h1>
			<p>Prozess: #{processDefinitionKey}</p>
			<FORM class="form-horizontal" ENCTYPE="multipart/form-data" ACTION="startByUpload" METHOD="POST">
				<fieldset>
					<div class="control-group">
						<label class="control-label" for="invoice">Rechnung (PDF)</label>
						<div class="controls">
							<INPUT NAME="invoice" TYPE="file" /> 
							<input type="hidden" name="processDefinitionKey" value="#{processDefinitionKey}" />
							<input type="hidden" name="callbackUrl" value="#{callbackUrl}" />
						</div>
					</div>
				</fieldset>
				<INPUT class="btn btn-primary" TYPE="submit" VALUE="Prozess starten" />
			</FORM>
		</div>
	</h:body>

</ui:composition>